### PR TITLE
Styling carousel

### PR DESCRIPTION
**Pull request by Dromediansk**
I've changed some basic style of carousel to fit the whole screen and look prittier. Currently working only on large screens (laptops).

### CODE REVIEW

**Comment by MattCSmith** [comment]
Hey @Dromediansk,
What was the z-index fix for? it appears to break the slider for me, since you can no longer click the arrows or slide markers.

**Comment by Dromediansk** [comment]
Hi @MattCSmith,
when I'd changed height of carousel to fit the whole screen, it was overlapping the image banner (html, css, js image) beneath it. Negative value of z-index solved the problem.

**Comment by MattCSmith** [comment]
Hi @Dromediansk,
I have checked on a couple of browsers and I'm not sure the z-index change is the best solution here. 

As you can see in the screen shot below, the slider does not fill the screen and in addition the buttons in red are unclickable. Removing the z-index fixed both problems. Maybe the better fix for this issue would be to add some padding or a margin to the section beneath it?

image

Regards
Matt

**Comment by Dromediansk** [comment]
@MattCSmith thank you for the suggestions! I fixed the issue and created another pull request, so it should be fine.

**Pull request merged**
